"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updatePackageController = exports.updatePackageUseCase = exports.getByIdPackageController = exports.getAllPackageController = exports.createPackageController = exports.getByIdPackageUseCase = exports.getAllPUseCase = exports.createPackageUseCase = exports.mysqlPackageRepository = void 0;
const CreatePackageUseCase_1 = require("../application/CreatePackageUseCase");
const GetAllPackageUseCase_1 = require("../application/GetAllPackageUseCase");
const GetByIdPackageUseCase_1 = require("../application/GetByIdPackageUseCase");
const UpdatePackageUseCase_1 = require("../application/UpdatePackageUseCase");
const CreatePackageController_1 = require("./controllers/CreatePackageController");
const GetAllPackageController_1 = require("./controllers/GetAllPackageController");
const GetByIdPackageController_1 = require("./controllers/GetByIdPackageController");
const UpdatePackageController_1 = require("./controllers/UpdatePackageController");
const MysqlPackageRepository_1 = require("./MysqlPackageRepository");
exports.mysqlPackageRepository = new MysqlPackageRepository_1.MysqlPackageRepository();
exports.createPackageUseCase = new CreatePackageUseCase_1.CreatePackageUseCase(exports.mysqlPackageRepository);
exports.getAllPUseCase = new GetAllPackageUseCase_1.GetAllPackageUseCase(exports.mysqlPackageRepository);
exports.getByIdPackageUseCase = new GetByIdPackageUseCase_1.GetByIdPackageUseCase(exports.mysqlPackageRepository);
exports.createPackageController = new CreatePackageController_1.CreatePackageController(exports.createPackageUseCase);
exports.getAllPackageController = new GetAllPackageController_1.GetAllPackageController(exports.getAllPUseCase);
exports.getByIdPackageController = new GetByIdPackageController_1.GetByIdPackageController(exports.getByIdPackageUseCase);
exports.updatePackageUseCase = new UpdatePackageUseCase_1.UpdatePackageUseCase(exports.mysqlPackageRepository);
exports.updatePackageController = new UpdatePackageController_1.UpdatePackageController(exports.updatePackageUseCase);
